### ISSUE TITLE
Attached fixed colors to node alignment groups

### ISSUE THREAD

**Issue by wlongabaugh** [RishiDesai/BioFabric#16]
Instead of using the automatic color cycle for node group annotations, they should be assigned fixed colors from the cycle, so that a missing group will not cause the color assignment to change between alignments.

**Comment by RishiDesai** [comment]
Already done in push 10 days ago.

**Comment by wlongabaugh** [comment]
OK, but the pictures you shared today assign yellow or blue to what appear to be the same bottom node group across different alignments (normal or reduced)? Not clear why that would be?

**Comment by RishiDesai** [comment]
Those are the same node groups and they do have the same color: for some reason, from the fully zoomed out view the node group looks blue but after zooming in a certain amount the color of the node group turns yellow. This could be caused by some kind of color conflict (with link group annots?). But this doesn't happen in the other network alignment.

**Comment by wjrl** [comment]
OK, the color problem is because the low-res bucket renderer is still cycling and not paying attention to the color assignment. Have entered the bug into BioFabric main issue tracker.
