### ISSUE TITLE
Cached NetAlign Network Issue

### ISSUE THREAD

**Issue by RishiDesai** [RishiDesai/BioFabric#25]
When you close loader when new Net Align network is loading, the previous network doesn't come back. It is in the bottom view but not in the main view.

**Comment by wjrl** [comment]
The previous network is cached as a temporary file, but by the time the cancel button is being pressed, the cache file name has been replaced with another empty file name. Investigating.

**Comment by wjrl** [comment]
The alignment flow loads two separate files; the first load caches the previous network. By the time we get to a cancel down the line, the first cached file has been long forgotten. Though it is still there, it is not what is restored by the cancel. The restored file is empty, since it was the cache created after the first network has been tossed. Investigating.

**Comment by wjrl** [comment]
Using the first cached file now for all cancellations. Fix has been pushed, and this can be closed.
