### ISSUE TITLE
GW import should provide a relation dialog

### ISSUE THREAD

**Issue by wjrl** [RishiDesai/BioFabric#30]
Since GW files do not supply a link relation, there should be a pop-up dialog after file load for user to enter the text string they want.

**Comment by RishiDesai** [comment]
Dialog's text-field has a default value- if user cancels out (closes) the dialog, then the relation returned will be whatever was in the text-field. If the text in the text-field was empty or mis-formatted, then just return default relation. There is a warning dialog that pops up for this. User is not trapped into loading network because directionality dialog comes up next with option to cancel.
