### ISSUE TITLE
Code cruft? "This method is currently wrong"

### ISSUE THREAD

**Issue by wjrl** [RishiDesai/BioFabric#31]
Two methods in BioFabricPanel are apparently unused, but bogus. Should be fixed and used where they were intended, or dropped:  

private Rectangle2D findPoint(List<Rectangle2D> recList, Point2D p)
private Rectangle2D findPoint(List<Rectangle2D> recList, String nodeName)

**Comment by RishiDesai** [comment]
I made/edited those methods a long time ago when I did multiple drain zones back in winter of 2016. At the time it was plausible that I had to find the single node zone of a node given its node name only. The only thing is that nodes could have multiple zones (after I changed it) so finding a single one would not necessarily be possible because I had not information on which I should choose. But Because it is not used it needs to be deleted, as the functions had a flawed implementation.

**Comment by RishiDesai** [comment]
I totally forgot about those functions. I need to go searching around looking more closely for this kind of thing. I vaguely remember a function that pertained to network tours (i think) that was flawed just like this. I will find and fix it.

**Comment by RishiDesai** [comment]
1ee4a43c11bd72dc5dcea9125f3549e5b6d0dccc removed the cruft. Will be on look out.

**Comment by RishiDesai** [comment]
I found the other place- its goToDrainZone in BioFabricPanel. It already has a UiUtil fixme and is an issue in wjrl. github.com/wjrl/BioFabric/issues/61
